# Generated by Django 5.0.7 on 2024-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0002_alter_tasklist_name_task_alter_tasklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='number_task',
            field=models.IntegerField(default=0),
        ),
    ]
