# Generated by Django 5.0.7 on 2024-07-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
